const { ethers } = require('ethers');
const fs = require('fs');
const path = require('path');

// Omega Network RPC
const RPC_URL = 'https://0x4e454228.rpc.aurora-cloud.dev';
const CHAIN_ID = 1313161768;

// Contract bytecode and ABI (will be generated by Hardhat)
// For now, we'll use a deployment approach that compiles first
async function deploy() {
    // Get private key from command line argument
    const privateKey = process.argv[2];
    
    if (!privateKey) {
        console.error('Error: Private key required as argument');
        console.log('Usage: node deploy.js <private_key>');
        process.exit(1);
    }

    // Remove 0x prefix if present
    const cleanPrivateKey = privateKey.startsWith('0x') ? privateKey.slice(2) : privateKey;
    
    if (cleanPrivateKey.length !== 64) {
        console.error('Error: Invalid private key length');
        process.exit(1);
    }

    try {
        console.log('Connecting to Omega Network...');
        const provider = new ethers.JsonRpcProvider(RPC_URL);
        const wallet = new ethers.Wallet('0x' + cleanPrivateKey, provider);
        
        console.log('Deployer address:', wallet.address);
        
        // Check balance
        const balance = await provider.getBalance(wallet.address);
        console.log('Balance:', ethers.formatEther(balance), 'OMEGA');
        
        if (balance === 0n) {
            console.error('Error: Insufficient balance for deployment');
            process.exit(1);
        }

        // Read contract source
        const contractPath = path.join(__dirname, 'contracts', 'ClaimDistributor15.sol');
        const contractSource = fs.readFileSync(contractPath, 'utf8');
        
        console.log('\nCompiling contract...');
        // We'll use a simple approach: deploy using Hardhat or compile inline
        // For now, let's use a manual compilation approach or Hardhat
        
        console.log('\nNote: This script requires Hardhat for compilation.');
        console.log('Please run: npx hardhat compile');
        console.log('Then use the compiled artifacts to deploy.');
        
        // Alternative: Use Hardhat's deploy script
        console.log('\nTo deploy with Hardhat:');
        console.log('1. Run: npx hardhat compile');
        console.log('2. Run: npx hardhat run scripts/deploy.js --network omega');
        
        process.exit(0);
        
    } catch (error) {
        console.error('Deployment error:', error.message);
        process.exit(1);
    }
}

deploy();
